### ISSUE TITLE
Index alphabetical order is off

### ISSUE THREAD

**Issue by piperhaywood** [piperhaywood/commonplace-wp-theme#52]
V comes after Q... WTH is that about?! Related to #35

**Comment by benjifs** [comment]
I could be mistaken and don't have a way to test this well but I believe that there is a `sort` missing for `$groups`.

I tried replicating this with the following:
```
<?php

function cp_add_to_index($groups, $name) {
  $first_char = strtoupper($name[0]);
  $groups[$first_char][uniqid()] = array();
  return $groups;
}

$groups = array();
$groups = cp_add_to_index($groups, "zebra");
$groups = cp_add_to_index($groups, "alligator");
$groups = cp_add_to_index($groups, "Cat");
$groups = cp_add_to_index($groups, "Aardvark");
$groups = cp_add_to_index($groups, "lion");
$groups = cp_add_to_index($groups, "Yak");

foreach($groups as $char => $terms) {
    echo $char;
}
echo "\n";

ksort($groups);
foreach($groups as $char => $terms) {
    echo $char;
}
```

I could be missing something else or the list could be coming in sorted originally but just thought I'd share what I saw.

**Comment by piperhaywood** [comment]
Thanks so much for the suggestion! I’ll take a look and try to see if that’s the case… I’m on maternity leave at the moment so it will take me a bit, but will try to look soon!
